import React from "react";
import { VideoOrb } from "../../../design-system/components/Orb/VideoOrb";
import { CefrLevelCode } from "../../conversation/services/dynamicQuestionService";

export interface WritingTaskHeaderProps {
  category?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  spanishDescription?: string | undefined;
  currentLevel?: string | undefined;
  onSelectLevel?: ((level: CefrLevelCode) => void) | undefined;
  isActive?: boolean | undefined;
}

function getFallbackSpanishPrompt(prompt: string): string | null {
  const p = prompt.toLowerCase();
  if (
    p.includes("introducing your name") ||
    p.includes("introduce yourself") ||
    p.includes("introduce your name") ||
    p.includes("name and role") ||
    p.includes("name and your role")
  ) {
    return "Escribe dos oraciones sencillas presentándote con tu nombre y tu rol de trabajo.";
  }
  if (p.includes("greeting") || p.includes("say hello") || p.includes("good morning")) {
    return "Escribe un saludo corto diciendo que estás listo para trabajar.";
  }
  if (p.includes("tool") || p.includes("computer") || p.includes("laptop")) {
    return "Escribe dos oraciones sencillas sobre una herramienta o computador que uses en tu trabajo.";
  }
  if (p.includes("confirming the date") || p.includes("confirming") || p.includes("meeting") || p.includes("mediation session")) {
    return "Escribe un correo o mensaje breve confirmando la fecha y la hora de la sesión o reunión.";
  }
  if (p.includes("colleague") || p.includes("help") || p.includes("coworker") || p.includes("question")) {
    return "Escribe dos oraciones cortas pidiéndole ayuda o haciendo una pregunta a un compañero de equipo.";
  }
  if (p.includes("routine") || p.includes("daily")) {
    return "Escribe dos oraciones sencillas sobre lo que haces habitualmente en tu trabajo.";
  }
  if (p.includes("end of day") || p.includes("goodbye") || p.includes("finished")) {
    return "Escribe dos oraciones cortas despidiéndote al terminar tu jornada de trabajo.";
  }
  if (p.includes("like") || p.includes("enjoy")) {
    return "Escribe dos oraciones sencillas sobre lo que te gusta de tu trabajo.";
  }
  return "Escribe una o dos oraciones sencillas en inglés completando esta tarea básica.";
}

export const WritingTaskHeader: React.FC<WritingTaskHeaderProps> = React.memo(
  function WritingTaskHeader({
    category,
    title = "Introduce Yourself to the Team",
    description = "Write 2 short sentences: your name and your job.",
    spanishDescription,
    currentLevel,
    onSelectLevel: _onSelectLevel,
    isActive = true,
  }) {
    // Strip redundant "Professional: " or role prefix generated by task models
    const cleanTitle = title.replace(/^[^:]+:\s*/, "").trim() || title;
    const cleanCategory = category
      ? category.replace(/^WRITING TASK\s*·?\s*/i, "").trim()
      : undefined;

    // Use description as the primary prompt instruction; fallback to title if absent
    const questionPrompt = description?.trim() || cleanTitle;
    const contextTopic = description?.trim() && description.trim() !== cleanTitle ? cleanTitle : null;

    // Strict pedagogical rule: Spanish scaffolding is ONLY rendered for A1 and A2 learners.
    // For B1, B2, C1, and C2, learners must practice with authentic English immersion (zero Spanish).
    const isA1orA2 = currentLevel ? /^A[12]$/i.test(currentLevel.trim()) : false;
    const resolvedSpanish = isA1orA2 ? (spanishDescription || getFallbackSpanishPrompt(questionPrompt)) : null;

    return (
      <div className="relative w-full flex items-start justify-between gap-4 select-none pt-1 sm:pt-2 pb-2 sm:pb-3 shrink-0">
        {/* Editorial Question Prompt Hierarchy — Pure typography, zero boxy badges */}
        <div className="flex flex-col min-w-0 flex-1">
          {/* Section Header: Pure Inter Typography with Amethyst Specular Hairline (Identical to Interview HUD) */}
          <div className="flex items-center space-x-2.5 mb-1.5 sm:mb-2">
            <span className="text-[10.5px] sm:text-[11px] font-bold tracking-[0.22em] uppercase font-sans text-[#8264C3]">
              QUESTION
            </span>
            <span className="h-px w-8 bg-gradient-to-r from-[#8264C3]/50 to-transparent inline-block" />

            {cleanCategory && (
              <span className="text-[10.5px] sm:text-[11px] font-mono uppercase tracking-wider text-white/35">
                {cleanCategory}
              </span>
            )}

            {contextTopic && (
              <>
                <span className="hidden sm:inline text-white/20 text-xs">·</span>
                <span className="hidden sm:inline text-[11px] sm:text-xs font-sans text-white/50 truncate font-normal">
                  {contextTopic}
                </span>
              </>
            )}
          </div>

          {/* Main Question / Task Prompt — High-contrast, pristine typography */}
          <h1 className="text-[16px] sm:text-[19px] lg:text-[21px] font-sans font-light text-white/95 tracking-normal leading-[1.5] sm:leading-[1.6] select-text [text-wrap:pretty] max-w-3xl">
            {questionPrompt}
          </h1>

          {/* Bilingual Spanish Guidance (Crucial for beginners in A1/A2) */}
          {resolvedSpanish && (
            <p className="mt-1.5 sm:mt-2 text-[12.5px] sm:text-[14px] font-sans text-white/65 font-normal tracking-wide leading-relaxed select-text [text-wrap:pretty] max-w-3xl">
              {resolvedSpanish}
            </p>
          )}
        </div>

        {/* Video Orb — subtle executive presence on desktop */}
        <div className="pointer-events-none hidden sm:flex sm:w-16 sm:h-16 md:w-20 md:h-20 items-center justify-center shrink-0 z-10 opacity-95 animate-[fadeIn_0.7s_ease-out_both] rounded-full overflow-hidden self-center">
          <VideoOrb isActive={isActive} className="w-full h-full object-contain pointer-events-none" />
        </div>
      </div>
    );
  },
);

